# 例外処理



## 例外処理の基礎

### throw/try/catch

```c++
try{
   // ...
}catch(例外の型 変数名){
   // ...
}catch(例外の型 変数名){
   // ...
}

throw 例外;
```

### 強制終了

投げられた例外を誰も捕まえることができなければ、デフォルトで`std::terminate()`関数が呼ばれ、

プログラムを強制終了することになる。



## 例外処理の詳細

### 全てを捕まえるcatch節

catch節の最後に１つだけ記述できる

```c++
catch(...){
   
}
```



### 例外の再送出

例外が投げられると、処理が一気にcatch節にくるため、場合によってメモリリークが起きるかもしれない。

何も例外オブジェクトを指定しないthrow文で、catch節が捕まえた例外をもう１回投げることができる。

```c++
catch(...){	// ...じゃなくても良い
   throw;
}
```



### noexcept指定

関数にnoexcept指定すると、その関数から絶対に例外が投げられないことを宣言できる。

```c++
戻り値の型 関数名(引数) noexcept;
戻り値の型 関数名(引数) noexcept {   }
```



## new演算子の例外処理















## 標準例外



























